version: '3.8'

services:
  openvpn:
    image: mjenz/rpi-openvpn
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    volumes:
     - ./openvpn-data/conf:/etc/openvpn

