version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "/srv/dev-disk-by-uuid-6070b0d0-26aa-4186-b9ba-b702e441f203/mammothshare/navidrome/data:/data"
      - "/srv/dev-disk-by-uuid-6070b0d0-26aa-4186-b9ba-b702e441f203/mammothshare/navidrome/music:/music:ro"

#version: '3.8'
#
#services:
#  openvpn:
#    image: mjenz/rpi-openvpn
#    container_name: openvpn
#    ports:
#     - "1194:1194/tcp"
#    cap_add:
#      - NET_ADMIN
#    restart: unless-stopped
#    volumes:
#     - ./openvpn-data/conf:/etc/openvpn