version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "/mnt/kingston512ssd/falconShare/navidrome/data:/data"
      - "/mnt/kingston512ssd/falconShare/navidrome/media:/music:ro"

  spotdl:
    container_name: spotdl
    image: spotdl/spotify-downloader
    command: web --host 0.0.0.0 --web-use-output-dir
    environment:
      - PUID=1234 #CHANGE_TO_YOUR_UID
      - PGID=1234 #CHANGE_TO_YOUR_GID
      - TZ=Europe/Stockholm #CHANGE_TO_YOUR_TZ
      - UMASK=002
    ports:
      - 8800:8800
    volumes:
      - "/mnt/kingston512ssd/falconShare/navidrome/media:/music" #must use the :/music for config to work.
#    network_mode: host #your custom dockernetwork
    restart: unless-stopped
